[2022-01-26 23:32:12,416] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 manual__2022-01-27T02:29:43.157805+00:00 [queued]>
[2022-01-26 23:32:12,427] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 manual__2022-01-27T02:29:43.157805+00:00 [queued]>
[2022-01-26 23:32:12,428] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 23:32:12,428] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-26 23:32:12,428] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 23:32:12,440] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_3> on 2022-01-27 02:29:43.157805+00:00
[2022-01-26 23:32:12,446] {standard_task_runner.py:52} INFO - Started process 19981 to run task
[2022-01-26 23:32:12,450] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', 'manual__2022-01-27T02:29:43.157805+00:00', '--job-id', '939', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpv6x1j1rl', '--error-file', '/tmp/tmphvgn68hc']
[2022-01-26 23:32:12,450] {standard_task_runner.py:77} INFO - Job 939: Subtask task_3
[2022-01-26 23:32:12,517] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_3 manual__2022-01-27T02:29:43.157805+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-01-26 23:32:12,573] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-01-27T02:29:43.157805+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-27T02:29:43.157805+00:00
[2022-01-26 23:32:12,574] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-26 23:32:12,575] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-26 23:32:12,585] {subprocess.py:85} INFO - Output:
[2022-01-26 23:32:15,588] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-26 23:32:15,620] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20220127T022943, start_date=20220127T023212, end_date=20220127T023215
[2022-01-26 23:32:15,673] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-26 23:32:15,714] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
